'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Public ReadOnly Property Attachment_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Attachment_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Attachment_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Attachment_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Attachment_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Attachment_256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Attachment_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Attachment_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Attachment_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Attachment_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Attachment_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Attachment_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property buntuk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buntuk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Ccar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ccar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_AccessDetailView() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_AccessDetailView", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_AccountLink() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_AccountLink", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_AdvanceMoneyClosed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_AdvanceMoneyClosed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_AdvancePayClosed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_AdvancePayClosed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_AdvanceReceive() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_AdvanceReceive", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_ApproveGoodsReceipt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_ApproveGoodsReceipt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_ApprovePO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_ApprovePO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_ApprovePR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_ApprovePR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_APVatInput() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_APVatInput", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_Asset() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_Asset", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_AssetReturn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_AssetReturn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_AssetType() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_AssetType", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_AssetTypeCut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_AssetTypeCut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_AssetWithdraw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_AssetWithdraw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_AssetWriteoff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_AssetWriteoff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_BankBranch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_BankBranch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_BankTransfer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_BankTransfer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_BankTransferOut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_BankTransferOut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_BOQ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_BOQ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_BOQPanelView() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_BOQPanelView", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_BOQPreview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_BOQPreview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_BOQSummary() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_BOQSummary", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_Budget() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_Budget", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_CalcMatCost() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_CalcMatCost", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_ChangePasswordIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_ChangePasswordIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_CloseAccountPeriod() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_CloseAccountPeriod", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_ContactUsIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_ContactUsIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_CostCenterBudgetDetailView() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_CostCenterBudgetDetailView", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_DatabaseSelectionIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_DatabaseSelectionIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_DebugIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_DebugIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_DR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_DR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_EntityAutoGen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_EntityAutoGen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_ErrorTestIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_ErrorTestIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_ExportOutgoingCheck() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_ExportOutgoingCheck", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_ExportPaymentTrackDetail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_ExportPaymentTrackDetail", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_ExportPC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_ExportPC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_FFormat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_FFormat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_Flow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_Flow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_FormTesterIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_FormTesterIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_GlAtomListIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_GlAtomListIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_GLFormat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_GLFormat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_GLListIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_GLListIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_GLYearEnd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_GLYearEnd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_GoodsSold() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_GoodsSold", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_Help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_Help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_InternalChargeDetail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_InternalChargeDetail", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_ItemListing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_ItemListing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_JournalEntry() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_JournalEntry", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_JournalEntryUpdate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_JournalEntryUpdate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_LaborGroup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_LaborGroup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_LinkFormIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_LinkFormIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_LinkrepostIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_LinkrepostIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_LKIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_LKIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_Loan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_Loan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_LogOffIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_LogOffIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_MappingListIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_MappingListIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_Markup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_Markup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_MarkupDistibution() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_MarkupDistibution", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_MatEquipmentDetail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_MatEquipmentDetail", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_MaterialDetailView() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_MaterialDetailView", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_MatLabDetail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_MatLabDetail", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_MatOperationReturn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_MatOperationReturn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_MatOperationWithdraw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_MatOperationWithdraw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_MatReceipt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_MatReceipt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_MatSupDetail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_MatSupDetail", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_MatTransfer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_MatTransfer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_MultiApproval() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_MultiApproval", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_NoteEntity2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_NoteEntity2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_NoteEntityIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_NoteEntityIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_OpenningBalance() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_OpenningBalance", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_OutgoingCheck() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_OutgoingCheck", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_PA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_PA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_PAAccountPanelView() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_PAAccountPanelView", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_Payment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_Payment", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_PettyCashClosed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_PettyCashClosed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_POPlaceOfDelivery() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_POPlaceOfDelivery", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_PrintPreviewList() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_PrintPreviewList", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_Receive() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_Receive", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_SaleBillIssue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_SaleBillIssue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_SaveAsIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_SaveAsIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_SC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_SC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_SchemaDataExport() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_SchemaDataExport", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_scWBSView() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_scWBSView", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_ShowCode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_ShowCode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_ShowPrintLog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_ShowPrintLog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_StockSequence() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_StockSequence", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_TestIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_TestIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_ToolDetailView() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_ToolDetailView", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_ToolLotDetailView() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_ToolLotDetailView", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_ToolsIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_ToolsIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_Unit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_Unit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_Vat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_Vat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_ViewBuilder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_ViewBuilder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_VO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_VO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_WitholdingTax() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_WitholdingTax", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Icons_16x16_WR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_16x16_WR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property juraa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("juraa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property KJ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KJ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property rabkug() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rabkug", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property VC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
